tesco/urls.py
from django.urls import path
from tesco import views

app_name = 'tesco'
urlpatterns = [
    path('', views.TescoProductList.as_view(), name='product_list'),
    path('upload_csv', views.tesco_product_upload, name="upload_csv"),
    path('search', views.tesco_product_list, name='search'),

]

upstylemini/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from product import views as myapp_views
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('product.urls', namespace='product')),
    path('tesco/', include('tesco.urls', namespace='tesco')),
    path('comparison/', include('comparison.urls', namespace='comparison')),
    path('salevelocity/', include('salevelocity.urls', namespace='salevelocity')),

    path('logout/', LogoutView.as_view(), {'next_page': '/accounts/login/'}, name='logout'),

]
handler404 = myapp_views.error404
handler500 = myapp_views.error500

tesco/models.py
from django.db import models


# Create your models here.
class TescoProducts(models.Model):
    image_link = models.CharField(max_length=500, null=True, blank=True)
    name = models.CharField(max_length=500, null=True, blank=True)
    price = models.CharField(max_length=500, null=True, blank=True)
    product_link = models.CharField(max_length=500, null=True, blank=True)
    product_id = models.IntegerField(primary_key=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-pk']

tesco/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.views import generic
from tesco import models
import csv
import io
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from tesco.filters import TescoProductFilter


# Create your views here.
class TescoProductList(LoginRequiredMixin, generic.ListView):
    template_name = 'tesco/tesco_products.html'
    context_object_name = 'tesco_products'
    paginate_by = 30

    def get_queryset(self):
        result = models.TescoProducts.objects.all()
        return result

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     context = super(ProductList, self).get_context_data()
    #
    #     context["categories"] = models.Category.objects.all()
    #     context["brands"] = models.Brand.objects.all()
    #
    #     return context


def tesco_product_upload(request):
    template_name = 'tesco/tesco_csv_upload.html'
    if request.method == "GET":
        return render(request, template_name)

    if 'tesco' in request.FILES:
        # let's check if it is a csv file
        csv_file = request.FILES['tesco']
        if not csv_file.name.endswith('.csv'):
            return render(request, template_name, {'message': 'Not a CSV FILE'})
        data_set = csv_file.read().decode('UTF-8')

        # setup a stream which is when we loop through each line we are able to handle a data in a stream

        io_string = io.StringIO(data_set)
        # next(io_string)
        str_headers = next(io_string)
        # print(headers)
        headers = str_headers.replace(', ', ' ').replace('"', '').replace('\ufeff', '').replace('\r\n', '').split(',')
        column_name = headers.index('name')
        column_price = headers.index('price')
        column_product_link = headers.index('product_link')
        column_product_id = headers.index('id')

        for column in csv.reader(io_string, delimiter=','):
            image_id = int(column[column_product_id]) % 1000
            image_link = 'https://img.tesco.com/Groceries/pi/{}/{}/IDShot_225x225.jpg'.format(image_id,
                                                                                              column[column_product_id])
            product_link = 'https://www.tesco.com{}'.format(column[column_product_link])
            tesco, created = models.TescoProducts.objects.update_or_create(product_id=int(column[column_product_id]),
                                                                           defaults={
                                                                               'name': column[column_name],
                                                                               'price': column[column_price],
                                                                               'product_link': product_link,
                                                                               'image_link': image_link,
                                                                           })
            print('name:{},price{},{}'.format(tesco.name, tesco.price, tesco.image_link))

        return render(request, template_name)


def tesco_product_list(request):
    f = TescoProductFilter(request.GET)
    context = {'filter': f}
    # filter_data = f.data

    if f.is_valid():
        context = {'filter': f}
        name = request.GET.get('name', '')

        filtered_products = models.TescoProducts.objects.filter(name__icontains=name) if name else models.TescoProducts.objects.all()[:30]

        page = request.GET.get('page', 1)

        paginator = Paginator(filtered_products, 30)

        try:
            filtered_products = paginator.page(page)
        except PageNotAnInteger:
            filtered_products = Paginator.page(1)
        except EmptyPage:
            filtered_products = paginator.page(paginator.num_pages)

        context['page_obj'] = filtered_products

    else:
        f = TescoProductFilter()
        context = {'filter': f}
    return render(request, 'tesco/tesco_filter.html', context)

tesco/templates/tesco/tesco_csv_upload.html
{% extends 'base.html' %}

{% block search %}


    <a href="{% url 'tesco:search' %}" type="button" class="btn btn-primary">
        <span class="glyphicon glyphicon-search"></span> Search
    </a>


    <a href="{% url 'tesco:product_list' %}" type="button" class="btn btn-primary">
        <span class="glyphicon glyphicon-home"></span> Product List
    </a>
{% endblock %}


{% block products %}

    <style>
        img {
            max-width: 180px;
        }

        input[type=file] {
            padding: 10px;
            border-style: solid;
            border-color: #FE9811;

        }
    </style>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row1">
            <div class="col-md-8">
                <label>
                    <input type="file" id="tesco" name="tesco">
                </label>
                <button class="btn btn-primary search-file-btn " style="min-width: 150px" type="submit">Upload Tesco Products
                </button>
            </div>
        </div>
    </form>
    
{% endblock %}

tesco/templates/tesco/tesco_filter.html
{% extends 'base.html' %}
{% load qurl %}
{% load static %}
{% load widget_tweaks %}


{% block search %}


    <a href="{% url 'tesco:product_list' %}" type="button" class="btn btn-primary">
        <span class="glyphicon glyphicon-home"></span> Product List
    </a>
{% endblock %}


{% block section %}



    {% block products %}

        <form method="get">
            <div class="row" style="margin-left: 50px">
                <div class="form-group col-sm-4 col-md-3">
                    {{ filter.form.name.label_tag }}
                    {% render_field filter.form.name class="form-control" %}
                </div>

                <div>
                    <button type="submit" class="btn btn-primary col-sm-4 col-md-3" style="margin-left: 50px">
                        <span class="glyphicon glyphicon-search"></span> Search
                    </button>
                </div>

            </div>
        </form>
        {% if page_obj %}
            <hr>
            {% for product in page_obj %}

                <div class="col-sm-4" style="min-height: 650px; max-height: 650px; max-width: 400px">
                    <div class="product-image-wrapper">
                        <div class="single-products">
                            <div class="productinfo text-center">
                                <img style="object-fit: cover; width: 100%; max-height: 300px; min-height: 300px;"
                                     src={{ product.image_link }} alt=""/>
                                <h2><b>Price: </b>{{ product.price }}</h2>
                                <p><b>ID: </b>{{ product.product_id }}</p>
                                <p><b>Name: </b>{{ product.name }}</p>

                                <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add
                                    to
                                    cart</a>
                            </div>
                            <div class="product-overlay">
                                <div class="overlay-content">
                                    <p><a href="{{ product.product_link }}">product
                                        link</a></p>
                                    <p></p>
                                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add
                                        to cart</a>
                                </div>
                            </div>
                        </div>
                        <div class="choose">
                            <ul class="nav nav-pills nav-justified">
                                <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                                <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

            {% endfor %}
        {% endif %}


    {% endblock %}

{% endblock %}

{% block footer %}

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="{% qurl request.get_full_path page=None %}&page=1" type="button" class="btn btn-primary">&laquo; first</a>
                <a href="{% qurl request.get_full_path page=None %}&page={{ page_obj.previous_page_number }}"
                   type="button"
                   class="btn btn-primary">previous</a>
            {% endif %}

            <a class="btn btn-primary"> {{ page_obj.number }}</a>

            {% if page_obj.has_next %}
                <a href="{% qurl request.get_full_path page=None %}{% if request.get_full_path == '/search' %}?{% else %}&{% endif %}page={{ page_obj.next_page_number }}"
                   type="button"
                   class="btn btn-primary">next</a>
                <a href="{% qurl request.get_full_path page=None %}&page={{ page_obj.paginator.num_pages }}"
                   type="button"
                   class="btn btn-primary">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

tesco/templates/tesco/tesco_products.html
{% extends 'base.html' %}
{% load static %}

{% block search %}


    <a href="{% url 'tesco:search' %}" type="button" class="btn btn-primary">
        <span class="glyphicon glyphicon-search"></span> Search
    </a>
    <a href="{% url 'tesco:upload_csv' %}" type="button" class="btn btn-primary">
        <span class="glyphicon glyphicon-shopping-cart"></span> Upload Tesco
    </a>
{% endblock %}

{% block products %}
    <div class="col-sm-9 padding-right">
        <div class="features_items"><!--features_items-->
            <h2 class="title text-center">Features Items</h2>


            {% for product in tesco_products %}

                <div class="col-sm-4" style="min-height: 650px; max-height: 650px; max-width: 400px">
                    <div class="product-image-wrapper">
                        <div class="single-products">
                            <div class="productinfo text-center">
                                <img style="object-fit: cover; width: 100%; max-height: 300px; min-height: 300px;"
                                     src={{ product.image_link }} alt=""/>
                                <h2><b>Price: </b>{{ product.price }}</h2>
                                <p><b>ID: </b>{{ product.product_id }}</p>
                                <p><b>Name: </b>{{ product.name }}</p>

                                <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add
                                    to
                                    cart</a>
                            </div>
                            <div class="product-overlay">
                                <div class="overlay-content">
                                    <p><a href="{{ product.product_link }}">product
                                        link</a></p>
                                    <p></p>
                                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add
                                        to cart</a>
                                </div>
                            </div>
                        </div>
                        <div class="choose">
                            <ul class="nav nav-pills nav-justified">
                                <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                                <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

            {% endfor %}


        </div>
    </div>
    {% if is_paginated %}
        <div class="logo pull-right">
            <nav aria-label="Page navigation conatiner"></nav>
            <ul class="pagination justify-content-center ">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
                {% endif %}
                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

                {% endif %}
            </ul>
            </nav>
        </div>
        </div>
    {% endif %}
{% endblock %}

{% block categories %}
    {% for category in categories %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><a href="#">{{ category.category }}</a></h4>
            </div>
        </div>
    {% endfor %}
{% endblock %}

{% block brands %}
    {#    {% for brand in brands %}#}
    {#        <li><a href="#"> <span class="pull-right">(5)</span>{{ brand.brand }}</a></li>#}
    {##}
    {#    {% endfor %}#}
{% endblock %}