comparison/urls.py
from django.urls import path
from comparison import views

app_name = 'comparison'
urlpatterns = [

    path('compare', views.comparison_list, name='compare'),
]

salevelocity/urls.py
from django.urls import path
from salevelocity import views

app_name = 'salevelocity'
urlpatterns = [
    path('', views.salevelocity_upload, name='sale_velocity'),
    path('history_data', views.HistoryData.as_view(), name='history_data'),

    # path('error', views.handler404, name='error')

]

tesco/urls.py
from django.urls import path
from tesco import views

app_name = 'tesco'
urlpatterns = [
    path('', views.TescoProductList.as_view(), name='product_list'),
    path('upload_csv', views.tesco_product_upload, name="upload_csv"),
    path('search', views.tesco_product_list, name='search'),

]

upstylemini/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from product import views as myapp_views
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('product.urls', namespace='product')),
    path('tesco/', include('tesco.urls', namespace='tesco')),
    path('comparison/', include('comparison.urls', namespace='comparison')),
    path('salevelocity/', include('salevelocity.urls', namespace='salevelocity')),

    path('logout/', LogoutView.as_view(), {'next_page': '/accounts/login/'}, name='logout'),

]
handler404 = myapp_views.error404
handler500 = myapp_views.error500

salevelocity/models.py
from django.db import models


# Create your models here.
class SaleVelocity(models.Model):
    asin = models.CharField(max_length=500, null=True, blank=True)
    title = models.CharField(max_length=500, null=True, blank=True)
    sessions = models.IntegerField()
    session_percentage = models.DecimalField(max_digits=19, decimal_places=10)
    page_views = models.IntegerField()
    page_views_percentage = models.DecimalField(max_digits=19, decimal_places=10)
    buy_box_percentage = models.DecimalField(max_digits=19, decimal_places=10)
    units_ordered = models.IntegerField()
    units_ordered_b2b = models.IntegerField()
    unit_session_percentage = models.DecimalField(max_digits=19, decimal_places=10)
    unit_session_percentage_b2b = models.DecimalField(max_digits=19, decimal_places=10)
    ordered_product_sales = models.DecimalField(max_digits=19, decimal_places=10)
    ordered_product_sales_b2b = models.DecimalField(max_digits=19, decimal_places=10)
    total_order_items = models.IntegerField()
    total_order_items_b2b = models.IntegerField()
    average_selling_price = models.DecimalField(max_digits=19, decimal_places=10)
    sales_velocity = models.DecimalField(max_digits=19, decimal_places=10)
    days = models.IntegerField()
    datetime = models.DateTimeField(blank=True)

    def __str__(self):
        return '-'.join([self.asin, str(self.average_selling_price), str(self.sales_velocity), str(self.days)])

    class Meta:
        ordering = ['datetime', ]

salevelocity/forms.py
from django import forms

from django.conf import settings
from salevelocity import models
import datetime


class SaleVelocityForm(forms.ModelForm):
    start_date = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS, widget=forms.SelectDateWidget)
    end_date = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS, widget=forms.SelectDateWidget,
                               initial=datetime.date.today())
    download = forms.BooleanField(required=False)

    class Meta:
        model = models.SaleVelocity
        fields = ['datetime']

salevelocity/views.py
from django.shortcuts import render, HttpResponse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from salevelocity import models
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from salevelocity.forms import SaleVelocityForm
import csv
import io
import re
import datetime
from django.utils import timezone
import pytz
import tablib


# Create your views here.
def find_int_vale(text):
    text = text.split('.')
    whole = re.findall(r'[0-9]+', text[0])
    whole = ''.join(whole)
    try:
        decimal = re.findall(r'[0-9]+', text[1])
        decimal = ''.join(decimal)
    except:
        decimal = '0'
    final_value = '.'.join([whole, decimal])
    return float(final_value)


def salevelocity_upload(request):
    # declaring template
    template = "salevelocity/csv_upload.html"

    if request.method == "GET":
        return render(request, template)

    if 'salevelocity' in request.FILES:
        # let's check if it is a csv file
        csv_file = request.FILES['salevelocity']
        days = find_int_vale(request.POST.get('days', ''))

        if not csv_file.name.endswith('.csv'):
            return render(request, template, {'message': 'Not a CSV FILE'})
        data_set = csv_file.read().decode('UTF-8')

        # setup a stream which is when we loop through each line we are able to handle a data in a stream

        io_string = io.StringIO(data_set)
        # next(io_string)
        str_headers = next(io_string)
        # print(headers)
        headers = str_headers.replace(', ', ' ').replace('"', '').replace('\ufeff', '').split(',')
        asin = headers.index('(Parent) ASIN')
        title = headers.index('Title')
        sessions = headers.index('Sessions')
        session_percentage = headers.index('Session Percentage')
        page_views = headers.index('Page Views')
        page_views_percentage = headers.index('Page Views Percentage')
        buy_box_percentage = headers.index('Buy Box Percentage')
        units_ordered = headers.index('Units Ordered')
        units_ordered_b2b = headers.index('Units Ordered – B2B')
        unit_session_percentage = headers.index('Unit Session Percentage')
        unit_session_percentage_b2b = headers.index('Unit Session Percentage – B2B')
        ordered_product_sales = headers.index('Ordered Product Sales')
        ordered_product_sales_b2b = headers.index('Ordered Product Sales – B2B')
        total_order_items = headers.index('Total Order Items')
        total_order_items_b2b = headers.index('Total Order Items – B2B')

        for column in csv.reader(io_string, delimiter=','):
            average_selling_price = (find_int_vale(column[ordered_product_sales]) + find_int_vale(
                column[ordered_product_sales_b2b])) / (find_int_vale(column[total_order_items]) + find_int_vale(
                column[total_order_items_b2b]))
            sales_velocity = (find_int_vale(column[buy_box_percentage]) * find_int_vale(
                column[sessions]) * average_selling_price) / days / 100
            object = models.SaleVelocity.objects.create(asin=column[asin],
                                                        title=column[title],
                                                        sessions=find_int_vale(column[sessions]),
                                                        session_percentage=find_int_vale(
                                                            column[session_percentage]) / 100,
                                                        page_views=find_int_vale(column[page_views]),
                                                        page_views_percentage=find_int_vale(
                                                            column[page_views_percentage]) / 100,
                                                        buy_box_percentage=find_int_vale(
                                                            column[buy_box_percentage]),
                                                        units_ordered=find_int_vale(column[units_ordered]),
                                                        units_ordered_b2b=find_int_vale(
                                                            column[units_ordered_b2b]),
                                                        unit_session_percentage=find_int_vale(
                                                            column[unit_session_percentage]) / 100,
                                                        unit_session_percentage_b2b=find_int_vale(
                                                            column[unit_session_percentage_b2b]) / 100,
                                                        ordered_product_sales=find_int_vale(
                                                            column[ordered_product_sales]),
                                                        ordered_product_sales_b2b=find_int_vale(
                                                            column[ordered_product_sales_b2b]),
                                                        total_order_items=find_int_vale(
                                                            column[total_order_items]),
                                                        total_order_items_b2b=find_int_vale(
                                                            column[total_order_items_b2b]),
                                                        average_selling_price=average_selling_price,
                                                        sales_velocity=sales_velocity,
                                                        days=days,
                                                        datetime=datetime.datetime.now(tz=timezone.utc)
                                                        )
            # print('average_selling_price:{},    sales_velocity{}'.format(object.average_selling_price,
            #                                                              object.sales_velocity))

        return render(request, template)


class HistoryData(LoginRequiredMixin, generic.FormView):
    template_name = 'salevelocity/history_data.html'

    form_class = SaleVelocityForm

    def get(self, request, *args, **kwargs):

        form = SaleVelocityForm(request.GET)

        print(form.errors)
        if form.is_valid():
            context = {'form': form}
            start_date_year = request.GET.get('start_date_year', '')
            start_date_month = request.GET.get('start_date_month', '')
            start_date_day = request.GET.get('start_date_day', '')
            end_date_year = request.GET.get('end_date_year', '')
            end_date_month = request.GET.get('end_date_month', '')
            end_date_day = request.GET.get('end_date_day', '')
            start_date = datetime.date(int(start_date_year), int(start_date_month), int(start_date_day))
            end_date = datetime.date(int(end_date_year), int(end_date_month), int(end_date_day))
            download = request.GET.get('download', '')

            salevelocity = models.SaleVelocity.objects.filter(datetime__range=(start_date, end_date))
            if download == 'on':
                headers = ('Timestamp', '(Parent) ASIN', 'Title', 'Sessions', 'Session Percentage', 'Page Views',
                           'Page Views Percentage', 'Buy Box Percentage', 'Units Ordered', 'Units Ordered – B2B',
                           'Unit Session Percentage', 'Unit Session Percentage – B2B', 'Ordered Product Sales',
                           'Ordered Product Sales – B2B', 'Total Order Items', 'Total Order Items – B2B',
                           'AverageSelling price', 'Sales Velocity based on 45 days sales', 'Days')
                response_data = tablib.Dataset(headers=headers)
                for item in salevelocity.all():
                    response_data.append(
                        [item.datetime.astimezone(pytz.timezone("Asia/Kolkata")).strftime('%Y-%m-%d %H:%M:%S'),
                         item.asin, item.title, item.sessions, item.session_percentage, item.page_views,
                         item.page_views_percentage, item.buy_box_percentage, item.units_ordered,
                         item.units_ordered_b2b, item.unit_session_percentage, item.unit_session_percentage_b2b,
                         item.ordered_product_sales, item.ordered_product_sales_b2b, item.total_order_items,
                         item.total_order_items_b2b, item.average_selling_price, item.sales_velocity, item.days])
                response = HttpResponse(content_type='text/csv')
                response[
                    'Content-Disposition'] = 'attachment; filename="salevelocity_{date}.csv"'.format(
                    date=datetime.datetime.now().strftime('%Y_%m_%d'))
                response.write(response_data.export('csv'))
                return response
            else:
                page = request.GET.get('page', 1)
                paginator = Paginator(salevelocity, 50)

                try:
                    salevelocity = paginator.page(page)
                except PageNotAnInteger:
                    salevelocity = Paginator.page(paginator.num_pages)
                except EmptyPage:
                    salevelocity = paginator.page(paginator.num_pages)

                context['salevelocity'] = salevelocity

            return render(request, self.template_name, context)
        else:
            form = SaleVelocityForm()
            context = {'form': form}
        return render(request, self.template_name, context)

salevelocity/templates/salevelocity/csv_upload.html
{% extends 'base.html' %}

{% block search %}



{% endblock %}


{% block products %}

    <style>
        img {
            max-width: 180px;
        }

        input[type=file] {
            padding: 10px;
            border-style: solid;
            border-color: #FE9811;

        }
    </style>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row1">
            <div class="col-md-8">
                <label>
                    <input type="file" id="salevelocity" name="salevelocity">
                </label>
                <label>
                    <input type="text" id="days" name="days" placeholder="days">
                </label>
                <button class="btn btn-primary search-file-btn " style="min-width: 120px" type="submit">Upload Products
                </button>
            </div>
        </div>
    </form>
    <div>
        {% if message %}
            <h4 class="row">{{ message }}</h4>
        {% endif %}
    </div>
{% endblock %}

salevelocity/templates/salevelocity/history_data.html
{% load static %}
{% load qurl %}
{% load widget_tweaks %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | E-Shopper</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'css/price-range.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">

    <script src="{% static 'js/html5shiv.js' %}"></script>
    {{ form.media.css }}

<body>
<header id="header"><!--header-->
    <div class="header_top"><!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="#"><i class="fa fa-phone"></i> +2 9999999999</a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> admin@upstyle.com</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            {#                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>#}
                            {#                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>#}
                            {#                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>#}
                            {#                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>#}
                            {#                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>#}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->

    <div class="header-middle"><!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="logo pull-left">
                        <a href="{% static 'index.html' %}"><img src="{% static 'images/home/logo.png' %}" alt=""/></a>
                    </div>
                    <div class="logo pull-right">
                        <a href="{% url 'product:product_list' %}" type="button" class="btn btn-primary">
                            <span class="glyphicon glyphicon-shopping-cart"></span> Amazon
                        </a>
                        <a href="{% url 'tesco:product_list' %}" type="button" class="btn btn-primary">
                            <span class="glyphicon glyphicon-shopping-cart"></span> Tesco
                        </a>
                        <a href="{% url 'comparison:compare' %}" type="button" class="btn btn-primary">
                            <span class="glyphicon glyphicon-search"></span> Compare
                        </a>
                        <a href="{% url 'salevelocity:history_data' %}" type="button" class="btn btn-primary">
                            <span class="glyphicon glyphicon-upload"></span> Sale Velocity
                        </a>
                        <a href="{% url 'logout' %}" type="button" class="btn btn-primary">
                            <span class="glyphicon glyphicon-log-out"></span> Logout
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->

</header><!--/header-->
{% block section %}
    <section>
        <div class="container">
            <div class="row">
                {% block products %}
                    <div class="row row-inline-block small-spacing">
                        <div class="col-xs-12">
                            <div class="box">
                                <div class="panel">
                                    <form action="" method="GET">
                                        <table class="table">
                                            <tr>
                                                {% csrf_token %}
                                                <div class="row" style="margin-left: 50px">
                                                    <div class="form-group col-sm-4 col-md-3">
                                                        {{ form.name.label_tag }}
                                                        {% render_field form.start_date class="form-control" %}
                                                    </div>
                                                    <div class="form-group col-sm-4 col-md-3">
                                                        {{ form.name.label_tag }}
                                                        {% render_field form.end_date class="form-control" %}
                                                    </div>
                                                    <div>
                                                        <h5>Download : </h5>{{ form.download }}
                                                    </div>
                                                </div>

                                                <button type="submit"
                                                        class="btn btn-primary col-sm-4 col-md-3"
                                                        style="margin-left: 50px">
                                                    <span class="glyphicon glyphicon-search"></span> Search
                                                </button>

                                                <a style="margin-left: 100px"
                                                   href="{% url 'salevelocity:sale_velocity' %}" type="button"
                                                   class="btn btn-primary">
                                                    <span class="glyphicon glyphicon-upload"></span> Upload CSV
                                                </a>

                                            </tr>

                                        </table>
                                    </form>
                                    <div class="box-body">
                                        <ul class="nav nav-tabs">
                                            <div class="table-responsive">
                                                <table class="table table-bordered">
                                                    <thead>
                                                    <tr>
                                                        <th>datetime</th>
                                                        <th>asin</th>
                                                        <th>title</th>
                                                        <th>sessions</th>
                                                        <th>buy_box_percentage</th>
                                                        <th>ordered_product_sales</th>
                                                        <th>ordered_product_sales_b2b</th>
                                                        <th>average_selling_price</th>
                                                        <th>sales_velocity</th>
                                                        <th>days</th>
                                                    </tr>
                                                    </thead>
                                                    <tbody>
                                                    {% for item in salevelocity %}
                                                        <tr>
                                                            <td>{{ item.datetime|date:'d/m/Y H:i' }}</td>
                                                            <td>{{ item.asin }}</td>
                                                            <td>{{ item.title }}</td>
                                                            <td>{{ item.sessions }}</td>
                                                            <td>{{ item.buy_box_percentage }}</td>
                                                            <td>{{ item.ordered_product_sales }}</td>
                                                            <td>{{ item.ordered_product_sales_b2b }}</td>
                                                            <td>{{ item.average_selling_price }}</td>
                                                            <td>{{ item.sales_velocity }}</td>
                                                            <td>{{ item.days }}</td>
                                                        </tr>
                                                    {% endfor %}
                                                    </tbody>
                                                </table>
                                            </div>
                                            <nav aria-label="Page navigation example">
                                                <ul class="pagination">
                                                    {% if salevelocity.has_previous %}
                                                        <li class="page-item"><a class="page-link"
                                                                                 href="{% qurl request.get_full_path page=None %}&page=1">&laquo;
                                                            first</a></li>
                                                        <li class="page-item"><a class="page-link" aria-label="Previous"
                                                                                 href="{% qurl request.get_full_path page=None %}&page={{ salevelocity.previous_page_number }}">previous</a>
                                                        </li>
                                                    {% endif %}


                                                    <li class="page-item active"><a class="page-link"
                                                                                    aria-label="Previous"
                                                                                    href="#">{{ salevelocity.number }}</a>
                                                    </li>



                                                    {% if salevelocity.has_next %}
                                                        <li class="page-item"><a class="page-link" aria-label="Next"
                                                                                 href="{% qurl request.get_full_path page=None %}&page={{ salevelocity.next_page_number }}">next</a>
                                                        </li>
                                                        <li class="page-item"><a class="page-link"
                                                                                 href="{% qurl request.get_full_path page=None %}&page={{ salevelocity.paginator.num_pages }}">last
                                                            &raquo;</a></li>
                                                    {% endif %}
                                                </ul>
                                            </nav>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endblock %}
            </div>
        </div>
    </section>
{% endblock %}

{% block footer %}
    <footer id="footer"><!--Footer-->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <p class="pull-left">Copyright © 2020 UPSTYLE BUSINESS. All rights reserved.</p>
                    <p class="pull-right">Designed by <span><a target="_blank">UPSTYLE</a></span></p>
                </div>
            </div>
        </div>

    </footer><!--/Footer-->
{% endblock %}

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
<script src="{% static 'js/price-range.js' %}"></script>
<script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{{ form.media }}
</body>
</html>