product/urls.py
from django.urls import path
from product import views
from django_filters.views import FilterView
from .filters import ProductFilter

app_name = 'product'
urlpatterns = [
    path('', views.ProductList.as_view(), name='product_list'),
    path('upload_csv', views.profile_upload, name="upload_csv"),
    path('search', views.product_list, name='search'),
    # path('error', views.handler404, name='error')

]

tesco/urls.py
from django.urls import path
from tesco import views

app_name = 'tesco'
urlpatterns = [
    path('', views.TescoProductList.as_view(), name='product_list'),
    path('upload_csv', views.tesco_product_upload, name="upload_csv"),
    path('search', views.tesco_product_list, name='search'),

]

upstylemini/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from product import views as myapp_views
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('product.urls', namespace='product')),
    path('tesco/', include('tesco.urls', namespace='tesco')),
    path('comparison/', include('comparison.urls', namespace='comparison')),
    path('salevelocity/', include('salevelocity.urls', namespace='salevelocity')),

    path('logout/', LogoutView.as_view(), {'next_page': '/accounts/login/'}, name='logout'),

]
handler404 = myapp_views.error404
handler500 = myapp_views.error500

product/models.py
from django.db import models


class Category(models.Model):
    category = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.category


class Brand(models.Model):
    brand = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.brand


class Products(models.Model):
    seller_id = models.CharField(max_length=500, null=True, blank=True)
    asin = models.CharField(primary_key=True, max_length=500)
    brand = models.ForeignKey(Brand, null=True, on_delete=models.SET_NULL)
    datetime = models.CharField(max_length=500, null=True, blank=True)
    image_link = models.CharField(max_length=500, null=True, blank=True)
    name = models.CharField(max_length=500, null=True, blank=True)
    price = models.CharField(max_length=500, null=True, blank=True)
    product_link = models.CharField(max_length=500, null=True, blank=True)
    rank = models.IntegerField(null=True)
    reviews = models.CharField(max_length=500, null=True, blank=True)
    ratings = models.CharField(max_length=500, null=True, blank=True)
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name


class Asins(models.Model):
    asin = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.asin

product/views.py
from django.shortcuts import render, redirect
from product import models
import csv
import io
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.views import generic
from tablib import Dataset
from . import filters
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import re
from .filters import ProductFilter


# Create your views here.
def error404(request, exception):
    data = {'status': exception}
    return render(request, '404.html', data)


def error500(request):
    data = {}
    return render(request, '404.html', data)


class ProductList(LoginRequiredMixin, generic.ListView):
    template_name = 'products.html'
    context_object_name = 'products'
    paginate_by = 20

    def get_queryset(self):
        result = models.Products.objects.all().order_by('rank')
        return result

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductList, self).get_context_data()

        context["categories"] = models.Category.objects.all()
        context["brands"] = models.Brand.objects.all()

        return context


def profile_upload(request):
    # declaring template
    template = "csv_upload.html"
    # data = models.Products.objects.last()
    # prompt is a context variable that can have different values      depending on their context
    # prompt = {
    #     'order': 'Order of the CSV should be name, email, address,    phone, profile',
    #     'profiles': data
    # }
    # GET request returns the value of the data with the specified key.
    if request.method == "GET":
        return render(request, template)

    if 'beauty' in request.FILES:
        # let's check if it is a csv file
        csv_file = request.FILES['beauty']

        if not csv_file.name.endswith('.csv'):
            return render(request, template, {'message': 'Not a CSV FILE'})
        data_set = csv_file.read().decode('UTF-8')

        io_string = io.StringIO(data_set)
        # next(io_string)
        str_headers = next(io_string)
        # print(headers)
        headers = str_headers.replace(', ', ' ').replace('"', '').replace('\ufeff', '').split(',')
        image_column = headers.index('Image')
        title_column = headers.index('Title')
        rank_column = headers.index('Sales Rank: Current')
        ratings_column = headers.index('Reviews: Rating')
        reviews_column = headers.index('Reviews: Review Count')
        last_price_change_column = headers.index('Last Price Change')
        price_column = headers.index('New: Current')
        seller_column = headers.index('Buy Box Seller')
        category_column = headers.index('Categories: Root')
        asin_column = headers.index('ASIN')
        brand_column = headers.index('Brand')

        for column in csv.reader(io_string, delimiter=','):

            try:
                image_link = column[image_column].split(";")[0]
            except AttributeError:
                image_link = column[image_column]
            category, created = models.Category.objects.get_or_create(category=str(column[category_column]))
            # print(created, end=' ')

            brand, created = models.Brand.objects.get_or_create(brand=str(column[brand_column]))
            # print(created, end=' ')

            # price = float(re.sub("[^0-9^.]", "", column[10]))
            product_link = "https://www.amazon.co.uk/dp/" + str(column[asin_column])
            asin, created = models.Products.objects.update_or_create(asin=str(column[asin_column]), defaults={
                'seller_id': str(column[seller_column]),
                'price': str(column[price_column]),
                'name': str(column[title_column]),
                'brand': brand,
                'product_link': str(product_link),
                'datetime': str(column[last_price_change_column]),
                'rank': int(column[rank_column]) if column[rank_column] else None,
                'ratings': str(column[ratings_column]),
                'reviews': str(column[reviews_column]),
                'image_link': str(image_link),
                'category': category,
            })
            # print('asin:{},category{},{}'.format(asin.asin, asin.category, str(created)))

        return render(request, template)


def product_list(request):
    f = ProductFilter(request.GET)
    context = {'filter': f}
    # filter_data = f.data

    if f.is_valid():
        context = {'filter': f}
        name = request.GET.get('name', '')
        brand = request.GET.get('brand', '')
        rank = request.GET.get('rank', '')
        category_id = request.GET.get('category', '')

        filtered_products = models.Products.objects.filter(name__icontains=name, brand__brand__icontains=brand,
                                                           rank__lte=int(rank) if rank else 100000, ).order_by(
            'rank') if name or rank or category_id or brand else models.Products.objects.all().order_by('rank')[:99]

        if category_id:
            category = models.Category.objects.get(pk=category_id)
            filtered_products = filtered_products.filter(category=category)
        #
        # if brand_id:
        #     brand = models.Brand.objects.get(brand__icontains=brand_id)
        #     filtered_products = filtered_products.filter(brand=brand)

        page = request.GET.get('page', 1)

        paginator = Paginator(filtered_products, 100)

        try:
            filtered_products = paginator.page(page)
        except PageNotAnInteger:
            filtered_products = Paginator.page(1)
        except EmptyPage:
            filtered_products = paginator.page(paginator.num_pages)

        context['page_obj'] = filtered_products

    else:
        f = ProductFilter()
        context = {'filter': f}
    return render(request, 'filter.html', context)

product/templates/csv_upload.html
{% extends 'base.html' %}

{% block search %}


    <a href="{% url 'product:search' %}" type="button" class="btn btn-primary">
        <span class="glyphicon glyphicon-search"></span> Search
    </a>


    <a href="{% url 'product:product_list' %}" type="button" class="btn btn-primary">
        <span class="glyphicon glyphicon-home"></span> Product List
    </a>
{% endblock %}


{% block products %}

    <style>
        img {
            max-width: 180px;
        }

        input[type=file] {
            padding: 10px;
            border-style: solid;
            border-color: #FE9811;

        }
    </style>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row1">
            <div class="col-md-8">
                <label>
                    <input type="file" id="beauty" name="beauty">
                </label>
                <button class="btn btn-primary search-file-btn " style="min-width: 120px" type="submit">Upload Products
                </button>
            </div>
        </div>
    </form>

{#    <form action="" method="POST" enctype="multipart/form-data">#}
{#        {% csrf_token %}#}
{#        <div class="row2">#}
{#            <div class="col-md-8">#}
{#                <label>#}
{#                    <input type="file" id="toys" name="toys">#}
{#                </label>#}
{#                <button class="btn btn-primary search-file-btn " style="min-width: 120px" type="submit">Upload Toys#}
{#                </button>#}
{#            </div>#}
{#        </div>#}
{#    </form>#}
{##}
{##}
{#    <form action="" method="POST" enctype="multipart/form-data">#}
{#        {% csrf_token %}#}
{#        <div class="row2">#}
{#            <div class="col-md-8">#}
{#                <label>#}
{#                    <input type="file" id="grocery" name="grocery">#}
{#                </label>#}
{#                <button class="btn btn-primary search-file-btn" style="min-width: 120px" type="submit">Upload Grocery#}
{#                </button>#}
{#            </div>#}
{#        </div>#}
{#    </form>#}





{% endblock %}

product/templates/filter.html
{% extends 'base.html' %}
{% load qurl %}
{% load static %}
{% load widget_tweaks %}


{% block search %}


    <a href="{% url 'product:product_list' %}" type="button" class="btn btn-primary">
        <span class="glyphicon glyphicon-home"></span> Product List
    </a>
{% endblock %}


{% block section %}



    {% block products %}

        <form method="get">
            <div class="row" style="margin-left: 50px">
                <div class="form-group col-sm-4 col-md-3">
                    {{ filter.form.name.label_tag }}
                    {% render_field filter.form.name class="form-control" %}
                </div>
                <div class="form-group col-sm-4 col-md-3">
                    {{ filter.form.rank.label_tag }}
                    {% render_field filter.form.rank class="form-control" %}
                </div>
                <div class="form-group col-sm-4 col-md-3">
                    {{ filter.form.brand.label_tag }}
                    {% render_field filter.form.brand class="form-control" %}
                </div>
                <div class="form-group col-sm-4 col-md-3">
                    {{ filter.form.seller_id.label_tag }}
                    {% render_field filter.form.seller_id class="form-control" %}
                </div>
            </div>
            <div class="row" style="margin-left: 50px">

                <div class="form-group col-sm-4 col-md-3">
                    {{ filter.form.category.label_tag }}
                    {% render_field filter.form.category class="form-control" %}
                </div>
                <div >
                    <button type="submit" class="btn btn-primary col-sm-4 col-md-3" style="margin-left: 500px">
                        <span class="glyphicon glyphicon-search"></span> Search
                    </button>
                </div>

            </div>


        </form>
        {% if page_obj %}
            <hr>
            {% for product in page_obj %}
                {% if forloop.counter|divisibleby:3 %}
                    {#                <h1>{{ forloop.counter }}</h1>#}

                {% endif %}

                <div class="col-sm-4" style="min-height: 650px; max-height: 650px; max-width: 400px">
                    <div class="product-image-wrapper">
                        <div class="single-products">
                            <div class="productinfo text-center">
                                <img style="object-fit: cover; width: 100%; max-height: 300px; min-height: 300px;"
                                     src={{ product.image_link }} alt=""/>
                                <h2><b>Price: </b>{{ product.price }}</h2>
                                <p><b>Asin: </b>{{ product.asin }}</p>
                                <p><b>Name: </b>{{ product.name }}</p>
                                <p><b>Brand: </b>{{ product.brand }}</p>

                                <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add
                                    to
                                    cart</a>
                            </div>
                            <div class="product-overlay">
                                <div class="overlay-content">
                                    <p><b>Seller id: </b>{{ product.seller_id }}</p>
                                    <p><b>Date: </b>{{ product.datetime }}</p>
                                    <p><b>Rank: </b>{{ product.rank }}</p>
                                    <p><b>Reviews: </b>{{ product.reviews }}</p>
                                    <p><b>Ratings: </b>{{ product.ratings }}</p>
                                    <p><b>Category: </b>{{ product.category }}</p>

                                    <p><a href="{{ product.product_link }}">product
                                        link</a></p>
                                    <p></p>
                                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add
                                        to cart</a>
                                </div>
                            </div>
                        </div>
                        <div class="choose">
                            <ul class="nav nav-pills nav-justified">
                                <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                                <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                            </ul>
                        </div>
                    </div>
                </div>





                {#            {% if is_paginated %}#}
                {#                <div class="logo pull-right">#}
                {#                    <nav aria-label="Page navigation conatiner"></nav>#}
                {#                    <ul class="pagination justify-content-center ">#}
                {#                        {% if filter.has_previous %}#}
                {#                            <li><a href="?page={{ filter.previous_page_number }}" class="page-link">&laquo; PREV </a>#}
                {#                            </li>#}
                {#                        {% endif %}#}
                {#                        {% if filter.has_next %}#}
                {#                            <li><a href="?page={{ filter.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>#}
                {##}
                {#                        {% endif %}#}
                {#                    </ul>#}
                {#                    </nav>#}
                {#                </div>#}
                {#                </div>#}
                {#            {% endif %}#}
            {% endfor %}
        {% endif %}


    {% endblock %}

{% endblock %}

{% block footer %}

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="{% qurl request.get_full_path page=None %}&page=1" type="button" class="btn btn-primary">&laquo; first</a>
                <a href="{% qurl request.get_full_path page=None %}&page={{ page_obj.previous_page_number }}"
                   type="button"
                   class="btn btn-primary">previous</a>
            {% endif %}

            <a class="btn btn-primary"> {{ page_obj.number }}</a>

            {% if page_obj.has_next %}
                <a href="

                        {% qurl request.get_full_path page=None %}{% if request.get_full_path == '/search' %}?{% else %}&{% endif %}page={{ page_obj.next_page_number }}"
                   type="button"
                   class="btn btn-primary">next</a>
                <a href="{% qurl request.get_full_path page=None %}&page={{ page_obj.paginator.num_pages }}"
                   type="button"
                   class="btn btn-primary">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

product/templates/products.html
{% extends 'base.html' %}
{% load static %}

{% block search %}


    <a href="{% url 'product:search' %}" type="button" class="btn btn-primary">
        <span class="glyphicon glyphicon-search"></span> Search
    </a>
    <a href="{% url 'product:upload_csv' %}" type="button" class="btn btn-primary">
        <span class="glyphicon glyphicon-shopping-cart"></span> Upload Amazon
    </a>
{% endblock %}

{% block products %}
    <div class="col-sm-9 padding-right">
        <div class="features_items"><!--features_items-->
            <h2 class="title text-center">Features Items</h2>


            {% for product in products %}

                <div class="col-sm-4" style="min-height: 650px; max-height: 650px">
                    <div class="product-image-wrapper">
                        <div class="single-products">
                            <div class="productinfo text-center">
                                <img style="object-fit: cover; width: 100%; max-height: 300px; min-height: 300px;"
                                     src={{ product.image_link }} alt=""/>
                                <h2><b>Price: </b>{{ product.price }}</h2>
                                <p><b>Asin: </b>{{ product.asin }}</p>
                                <p><b>Name: </b>{{ product.name }}</p>
                                <p><b>Brand: </b>{{ product.brand }}</p>

                                <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add
                                    to
                                    cart</a>
                            </div>
                            <div class="product-overlay">
                                <div class="overlay-content">
                                    <p><b>Seller id: </b>{{ product.seller_id }}</p>
                                    <p><b>Date: </b>{{ product.datetime }}</p>
                                    <p><b>Rank: </b>{{ product.rank }}</p>
                                    <p><b>Reviews: </b>{{ product.reviews }}</p>
                                    <p><b>Ratings: </b>{{ product.ratings }}</p>
                                    <p><b>Category: </b>{{ product.category }}</p>
                                    <p><a href="{{ product.product_link }}">product
                                        link</a></p>
                                    <p></p>
                                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add
                                        to cart</a>
                                </div>
                            </div>
                        </div>
                        <div class="choose">
                            <ul class="nav nav-pills nav-justified">
                                <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                                <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                            </ul>
                        </div>
                    </div>
                </div>


            {% endfor %}


        </div>
    </div>
    {% if is_paginated %}
        <div class="logo pull-right">
            <nav aria-label="Page navigation conatiner"></nav>
            <ul class="pagination justify-content-center ">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
                {% endif %}
                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

                {% endif %}
            </ul>
            </nav>
        </div>
        </div>
    {% endif %}
{% endblock %}

{% block categories %}
{#    #}
    {% for category in categories %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><a href="#">{{ category.category }}</a></h4>
            </div>
        </div>
    {% endfor %}
{% endblock %}

{% block brands %}
    {#    {% for brand in brands %}#}
    {#        <li><a href="#"> <span class="pull-right">(5)</span>{{ brand.brand }}</a></li>#}
    {##}
    {#    {% endfor %}#}
{% endblock %}